# Generated by Django 5.0.2 on 2024-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_taskmodel_priotiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='priotiry',
            field=models.IntegerField(choices=[(1, 'high'), (2, 'middum'), (3, 'low')], default=1),
        ),
    ]
