# Generated by Django 4.2.7 on 2024-03-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_taskmodel_priotiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='priotiry',
            new_name='priority',
        ),
    ]
